### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by YB221** [okankop/Efficient-3DCNNs#17]
dataset loading [0/4795]
dataset loading [1000/4795]
dataset loading [2000/4795]
dataset loading [3000/4795]
dataset loading [4000/4795]
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    pin_memory=True)
  File "/home/yashbhambhu_18je0949/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/yashbhambhu_18je0949/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Please help!

**Comment by YB221** [comment]
It was my bad. The solution is to arrange your data set in "/folder/classname/videoname/*.jpg" format otherwise it won't load hence num_samples will remain 0. 
Hope this helps.

**Comment by ArnabSen123** [comment]
Can you me how exactly have you solved this problem in details?
